name: Build Docker

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACTIONS_ROLE }}
#      AWS_DEFAULT_REGION: 
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          role-session-name: MySessionName
      - name: Login to Amazon ECR
        id: dev-cluster-1-app-img
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: app-docker
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
