
on:
  workflow_call:
    inputs:
      release_version: 
        default: "app-x.x.x-helm-x.x.x"
        type: string
        required: false
      app_ver: 
        default: "x.x.x"
        type: string
        required: false
      helm_ver: 
        default: "x.x.x"
        type: string
        required: false
        
jobs:
  build:
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   #
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      REPO_NAME: app
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::637423298449:role/github-dev-oidc-test4hiringband
          role-session-name: ECR_Push_Session
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR 
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPO_NAME:$IMAGE_TAG -t $REGISTRY/$REPO_NAME:${{inputs.app_ver}} .
          docker push $REGISTRY/$REPO_NAME:$IMAGE_TAG
          docker push $REGISTRY/$REPO_NAME:${{inputs.app_ver}}
        
      - name: Package and push helm chart to Amazon ECR
        working-directory: ./helm
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          VERSION=$(cat ../helm_version)
          helm package $REPO_NAME
          helm push $REPO_NAME-$VERSION.tgz oci://$REGISTRY
      - name: Build & Publish to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.actor }}/${{ env.REPO_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          registry: ghcr.io
          snapshot: false
          tags: "${{inputs.app_ver}}"




          # Release to github
      - name: Configure Git to release package
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release to github
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
