name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: production-deploy
  queue: max
jobs:
  #LINTING-TESTING STAGE
  linter:
    uses: ./.github/workflows/linter.yml
  check-app:
    uses: ./.github/workflows/check_app.yml
  #  check-infra:
  #    uses: ./.github/workflows/check_infra.yml
  #BUILD STAGE
  build:
    uses: ./.github/workflows/build.yml
  #RELASE HELM APP
  release:
    uses: ./.github/workflows/release.yml
