name: CI

on:
  workflow_dispatch:
concurrency:
  group: production-deploy
  queue: max
jobs:
  
  environment: ${{GITHUB_REF}}
  #LINTING-TESTING STAGE
  linter:
    uses: ./.github/workflows/linter.yml
  check-app:
    uses: ./.github/workflows/check_app.yml
  #BUILD STAGE
  build:
    uses: ./.github/workflows/build.yml
  #RELASE HELM APP
  release:
    uses: ./.github/workflows/release.yml
