name: CI
on:
  workflow_dispatch:
    inputs:
      release_scope:
        description: "Select scope "
        required: true
        default: "app-x.x.x-helm-x.x.x."
        type: string

  workflow_call:
    inputs:
      release_version: 
        default: "app-11.0.0-helm-10.0.2"
        type: string
        required: true
      helm_ver: 
        default: "x.x.x"
        type: string
        required: true
      app_ver: 
        default: "x.x.x"
        type: string
        required: true

concurrency:

  group: production-deploy
  queue: max
env: 

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    #LINTING-TESTING STAGE
  linter:
    uses: ./.github/workflows/linter.yml
  check-app:
    uses: ./.github/workflows/check_app.yml
    
  #BUILD-RELEASE STAGE
  build:
    uses: ./.github/workflows/build.yml
    with:
      release-version: ${{ inputs.release_version }}
      helm_ver: ${{ inputs.helm_ver}}
      app_ver: ${{ inputs.app_ver}}
    needs: 
    - check-app
#    - linter
