name: check_app

on:
  workflow_call: 

jobs:
  check_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    steps:
    - uses: actions/checkout@v4
    - name: Lint checks
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
