name: check_app

on:
  push:
    branches: [ "dev", "stage" ]
    paths:    [  "app" ]
  pull_request:
    branches: [ "dev", "stage" ]
    paths:    [ "app"  ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working_directory: ./app
      
steps:
    - uses: actions/checkout@v4
    - name: Lint checks
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
