name: Linter

on:
  workflow_call:
  push:
    branches:
      - dev
      - stage
  pull_request:
    branches:
      - dev
      - stage

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      - name: Super-linter
        uses: super-linter/super-linter@v8.6.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          FIX_RUST_2024:	true
          FIX_YAML_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
