name: MegaLinter

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call: 
  

permissions: read-all

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v7 # NOTE: Update with hash
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
