name: Release new version
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      release_scope:
        description: "Select scope "
        required: true
        default: "both_app_helm"
        type: choice
        options:
          - helm
          - app
          - both_helm_app    
jobs:
  change-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: update version
      run: |
        ./release.yml ${{inputs.release_scope}} ${{inputs.release_type}} 
    
        echo "app_ver=$(cat helm_version)" >> $GITHUB_ENV
        echo "helm_ver=$(cat helm_version)" >> $GITHUB_ENV
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{github.ref_name}}
        commit-message: '${{helm_ver}} $helm_ver ${{app_ver}}'
        force-add: 'true'
        files: helm_version app_version
        name: Release
        email: my.github@email.com 
