name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      release_scope:
        description: "Select scope "
        required: true
        default: "both_app_helm"
        type: choice
        options:
          - helm
          - app
          - both_helm_app    
jobs:
  change-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: update version
      id: update
      run: |
        ./release.sh ${{inputs.release_scope}} ${{inputs.release_type}} 
        echo "app_ver=$(cat app_version)" >> $GITHUB_OUTPUT
        echo "helm_ver=$(cat helm_version)" >> $GITHUB_OUTPUT
#   - name: push
#      uses: github-actions-x/commit@v2.9
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        push-branch: ${{github.ref_name}}
#        commit-message: ' app:${{ steps.update.outputs.app_ver }} helm:${{ steps.update.outputs.helm_ver }} '
#        force-add: 'true'
#        files: helm_version app_version app/Cargo.toml helm/app/Chart.yaml helm/app/values.yaml
#        name: 'Release app:${{ steps.update.outputs.app_ver }} helm:${{ steps.update.outputs.helm_ver }} '
#        email: my.github@email.com 

    - name: commit new version
      uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
      with:
        add: 'helm_version app_version app/Cargo.toml helm/app/Chart.yaml helm/app/values.yaml'
        author_name: Release
        author_email: release@github.com
        committer_name: Release
        committer_email: mail@example.com
        default_author: github_actions
        message: ' app:${{ steps.update.outputs.app_ver }} helm:${{ steps.update.outputs.helm_ver }} '
       # new_branch: custom-new-branch
  #      pathspec_error_handling: ignore
 #       tag: 'app-${{ steps.update.outputs.app_ver }}-helm-${{ steps.update.outputs.helm_ver }}'
 #       tag_push: '--force'
